package com.uptc.prg2.CovidRegister.controller;
/*
 * 
 * @author CovidRegister
 *
 */
public enum Command {

	ADD_REGISTER,
	INFORMATION,
	COMPANY_STATUS,
	TEMPERATURE_REPORT,
	STATUS_PER_MONTH,
	SYMPTOM,
	TYPE_EMPLOYEE_PER_STATUS,
	ENGLISH,
	SPANISH,
	BUTTON_ADD_ACCEPT,
	BUTTON_ADD_CLEAN_FIELDS,
	BUTTON_ADD_CANCEL;
}
